# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 21234
#    context-path: /geec-web

spring:
    datasource:
        url: jdbc:mysql://112.35.22.232:3306/geec_manager_1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: geecuser
        password: asiainfo123
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    #redis配置
    redis:
        host: 127.0.0.1
        port: 6379
        # REDIS (RedisProperties)
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器连接密码（默认为空）
        password: foobared
        # 连接池最大连接数（使用负值表示没有限制）
        # 连接超时时间（毫秒）
        timeout: 0
        pool:
            max-active: 1024
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: 1000
            # 连接池中的最大空闲连接
            max-idle: 200
            # 连接池中的最小空闲连接
            min-idle: 0
#solr配置
    data:
         solr:
            host: http://127.0.0.1:8025/solr


alert:
    phoneNumber: 15811388589
    #设置大点 否则会发短信告警，如果短信包是生产的 则会阻塞，所以避免告警
    maxTime: 999999999999999
    flumeAddr: http://112.35.22.232:8025/analyzeVesopera.gif
    systemType: 1